



<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<!-- bxSlider Javascript file -->
<script src="jquery.bxslider.min.js"></script>
<!-- bxSlider CSS file -->
<link href="jquery.bxslider.css" rel="stylesheet" />
<ul class="bxslider">

    <li><img src="D:/1/OSPanel/domains/maagsite.com/app/code/local/Magentotutorial/Helloworld/images/Al" title="Funky roots testing" /></li>
    <li><img src="D:/1/OSPanel/domains/maagsite.com/app/code/local/Magentotutorial/Helloworld/images/War.jpg" title="The long and winding road dancing" /></li>
    <li><img src="D:/1/OSPanel/domains/maagsite.com/app/code/local/Magentotutorial/Helloworld/images/er.jpg" title="Happy trees singing" /></li>
</ul>
<script>
    jQuery('.bxslider').bxSlider({
        mode: 'fade',
        captions: true
    });
</script>